In [1]:
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [10]:
pCTRval = pd.read_csv('E:\\web_economics\\pCTRval.csv')
df_val = pd.read_csv('E:\\web_economics\\validation.csv')

## Linear bidding -> Fajar

In [11]:
# Average CTR
avgCTR = df_val.click.sum() / df_val.bidid.count()
avgCTR

0.00075396415000550463

In [12]:
pCTRval['0']

0         1.579898e-04
1         7.349234e-03
2         8.290381e-04
3         8.284264e-04
4         4.504915e-04
5         1.162211e-03
6         5.998983e-04
7         3.028085e-04
8         1.102182e-04
9         1.094727e-03
10        2.396839e-03
11        1.140630e-03
12        2.071078e-04
13        1.111751e-03
14        2.164032e-04
15        2.632546e-04
16        1.009612e-03
17        2.666122e-04
18        1.585414e-04
19        1.736296e-04
20        1.226088e-04
21        1.448435e-04
22        1.504250e-04
23        4.938726e-07
24        2.094038e-04
25        2.373731e-04
26        3.660335e-04
27        2.459582e-04
28        6.536386e-05
29        1.815096e-04
              ...
299719    2.921805e-05
299720    2.736914e-05
299721    4.256950e-04
299722    1.052270e-04
299723    1.135409e-04
299724    2.980132e-04
299725    2.737981e-05
299726    4.796109e-05
299727    1.511225e-05
299728    2.573521e-04
299729    1.282607e-04
299730    1.043893e-04
299731    5.169622e-04
299732    3.796270e-04
299733    1.960612e-03
299734    5.830008e-05
299735    1.625662e-03
299736    2.783508e-04
299737    4.201091e-04
299738    2.589965e-04
299739    4.581732e-04
299740    1.504643e-03
299741    5.633098e-05
299742    1.432369e-04
299743    9.049254e-04
299744    3.692257e-04
299745    5.488169e-07
299746    4.751115e-04
299747    2.900788e-04
299748    1.530082e-04
Name: 0, dtype: float64

In [15]:
def linear_bid_generator():
    #bid = base_bid * pCTR / avgCTR
    bid_max = 300

    bids = []
    l_pctrval = list(pCTRval['0'])
    for base_bid in range(10, bid_max+10, 10):
        for p in l_pctrval:
            bid = base_bid * p / avgCTR
            bids.append(bid)

    bid_groups = [bids[x:x+len(pCTRval)] for x in range(0, len(bids), len(pCTRval))]
    return bid_groups

In [14]:
print(len(pCTRval), len(df_val))

299749 299749

In [26]:
data = pd.DataFrame(columns=['bid','clicks','imps','spent','CTR','CPC','CPM'])
lists = {'bid':[], 'clicks':[], 'imps':[], 'spent':[], 'ctr':[], 'cpc':[], 'cpm':[]}
bid_groups = linear_bid_generator()

maxi = 0
maxv = -1
for k in range(0,len(bid_groups)):
    budget = 6250000.0
    imps = 0
    clicks = 0
    spent = 0
    bid = bid_groups[k]
    check = bid >= df_val.payprice
    for i in range(0,len(check)):
        payprice = df_val.payprice[i]
        if budget < payprice:
            break
        if check[i]:
            imps = imps + 1
            clicks = clicks + df_val.click[i]
            budget = budget - payprice
            spent = spent + payprice
    ctr = ((clicks / imps) * 100)
    cpm = ((spent / imps) * 1000)
    cpc = (spent / clicks)
    if ctr * clicks > maxv:
        maxv = ctr * clicks
        maxi = k
    #lists['bid'] = bid
    lists['clicks'].append(clicks)
    lists['imps'].append(imps)
    lists['spent'].append(spent)
    lists['ctr'].append(ctr)
    lists['cpc'].append(cpc)
    lists['cpm'].append(cpm)
data.clicks = lists['clicks']
data.imps = lists['imps']
data.spent = lists['spent']
data.CTR = lists['ctr']
data.CPC = lists['cpc']
data.CPM = lists['cpm']
data

    bid  clicks    imps    spent       CTR           CPC           CPM
0   NaN      75   12800   450405  0.585938   6005.400000  35187.890625
1   NaN      95   25099   955084  0.378501  10053.515789  38052.671421
2   NaN     116   37332  1503680  0.310725  12962.758621  40278.581378
3   NaN     128   49002  2060418  0.261214  16097.015625  42047.630709
4   NaN     134   59790  2618158  0.224118  19538.492537  43789.228968
5   NaN     148   70151  3166594  0.210973  21395.905405  45139.684395
6   NaN     156   79674  3699750  0.195798  23716.346154  46436.102116
7   NaN     161   88774  4231295  0.181359  26281.335404  47663.674049
8   NaN     166   97406  4767789  0.170421  28721.620482  48947.590498
9   NaN     168  105576  5288503  0.159127  31479.184524  50091.905357
10  NaN     169  113092  5781612  0.149436  34210.721893  51123.085629
11  NaN     175  119670  6249950  0.146235  35714.000000  52226.539651
12  NaN     162  117635  6250000  0.137714  38580.246914  53130.445871
13  NaN     150  115635  6249912  0.129719  41666.080000  54048.618498
14  NaN     147  113810  6249984  0.129163  42516.897959  54915.947632
15  NaN     144  111998  6249971  0.128574  43402.576389  55804.309006
16  NaN     139  110319  6249781  0.125998  44962.453237  56651.900398
17  NaN     135  108869  6249861  0.124002  46295.266667  57407.168248
18  NaN     130  107492  6249933  0.120939  48076.407692  58143.238567
19  NaN     124  106304  6249993  0.116647  50403.169355  58793.582556
20  NaN     126  105170  6249901  0.119806  49602.388889  59426.652087
21  NaN     124  104118  6249874  0.119096  50402.209677  60026.834937
22  NaN     118  103105  6249954  0.114446  52965.711864  60617.370642
23  NaN     117  102186  6249899  0.114497  53417.940171  61161.988922
24  NaN     116  101444  6249860  0.114349  53878.103448  61608.966523
25  NaN     112  100609  6249926  0.111322  55802.910714  62120.943454
26  NaN     110   99889  6249999  0.110122  56818.172727  62569.442081
27  NaN     109   99103  6249954  0.109987  57339.027523  63065.235159
28  NaN     108   98427  6249924  0.109726  57869.666667  63498.064555
29  NaN     108   97900  6249997  0.110317  57870.342593  63840.623085

In [22]:
print(len(lists['bid']),len(lists['clicks']),len(lists['imps']))

299749 30 30